---
title: "Health Insurance and Age"
author: "Summer"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r createfile}
library(dplyr)
library(readr)
library(corrplot)
library(ggplot2)
library(tidyverse)

#Load File
file_path <- "/Users/summerjohnson/Desktop/4810 Group/NSDUH_2023_Tab.txt"
# Reading data
data_2023 <- read.csv("/Users/summerjohnson/Desktop/4810 Group/NSDUH_2023_Tab.txt")
# Parsing the data
data_2023 <- read_delim(file_path, delim = "\t")

```

```{r over18}

#Create a new subset where people are over 18
data_subset_adults <- data_2023[data_2023$CATAG6>1, ]
data_subset_adults2 <- data_subset_adults[data_subset_adults$IRWRKSTAT<50, ]

```

```{r mentalhealth}

#Mental Health recoding
variables_to_recode <- c(
  "IRDSTNRV30", "IRDSTHOP30", "IRDSTRST30", "IRDSTCHR30", "IRDSTNGD30", 
  "IRDSTNRV12", "IRDSTHOP12", "IRDSTRST12", "IRDSTCHR12", "IRDSTEFF12", "IRDSTNGD12"
)

cleaned_data <- data_subset_adults2
# Recode each variable and update it directly in the cleaned_data dataset
for (var in variables_to_recode) {
  cleaned_data[[var]] <- ifelse(
    data_subset_adults2[[var]] == 99, 99, # Keep "LEGITIMATE SKIP" as is
    6 - data_subset_adults2[[var]]        # Reverse the scale for all other values
  )
}
# List of variables you want to recode
more_variables_to_recode <- c("IRDSTHOP30", "IRDSTCHR30", "IRDSTNGD30", "IRDSTHOP12", 
                              "IRDSTCHR12", "IRDSTEFF12", "IRDSTNGD12", "IRIMPHHLD", 
                              "IRIMPWORK", "IRDSTNRV30", "IRDSTRST30", "IRDSTNRV12", 
                              "IRDSTRST12", "IRIMPGOUT", "IRIMPSOC")
# Recode each variable and update it directly in the cleaned_data dataset
for (var in more_variables_to_recode) {
  cleaned_data[[var]] <- ifelse(
    cleaned_data[[var]] == 99, 0,   # Recode "LEGITIMATE SKIP" (99) as 0
    cleaned_data[[var]]             # Keep other values as they are
  )
}
# Creating a running total for the depression column
depression_variables <- c("IRDSTHOP30","IRDSTCHR30","IRDSTNGD30","IRDSTHOP12","IRDSTCHR12","IRDSTEFF12","IRDSTNGD12","IRIMPHHLD","IRIMPWORK")
# Create a new variable in cleaned_data that sums the depression-related variables
cleaned_data$depression_score <- rowSums(cleaned_data[depression_variables], na.rm = TRUE)
# Calculate mental health score and classify mental health status as 0 or 1
cleaned_data <- cleaned_data %>%
  mutate(
    depression_status = ifelse(depression_score > 36, 1, 0)  
  )
sum(is.na(cleaned_data$depression_score))
# Creating a running total for the anxiety column
anxiety_variables <- c("IRDSTNRV30","IRDSTRST30","IRDSTNRV12","IRDSTRST12","IRIMPGOUT","IRIMPSOC")
# Create a new variable in cleaned_data that sums the anxiety-related variables
cleaned_data$anxiety_score <- rowSums(cleaned_data[anxiety_variables], na.rm = TRUE)
# Calculate mental health score and classify mental health status as 0 or 1
cleaned_data <- cleaned_data %>%
  mutate(
    anxiety_status = ifelse(anxiety_score > 24, 1, 0)  
  )
# Combining depression and anxiety scores
cleaned_data$mental_health_score <- rowSums(cleaned_data[c(depression_variables, anxiety_variables)], na.rm = TRUE)
# Calculate mental health score and classify mental health status as 0 or 1
cleaned_data <- cleaned_data %>%
  mutate(
    mental_health_status = ifelse(mental_health_score > 60, 1, 0)  # 1 for Poor Mental Health, 0 for Good Mental Health
  )
sum(cleaned_data$depression_status == 1)
sum(cleaned_data$anxiety_status == 1)
sum(cleaned_data$mental_health_status == 1)

```

```{r mutate}

#Create education level, insurance type, and private coverage 
data_subset_one <- cleaned_data %>%
  mutate(
    education_level = case_when(
      IREDUHIGHST2 == 1 | IREDUHIGHST2 == 2 | IREDUHIGHST2 == 3 | IREDUHIGHST2 == 4 ~ 1, #Less than high school
      IREDUHIGHST2 == 5 | IREDUHIGHST2 == 6 | IREDUHIGHST2 == 7 ~ 2, #some high school, no diploma
      IREDUHIGHST2 == 8 ~ 3, #high school diploma / GED
      IREDUHIGHST2 == 9 ~ 4, #some college
      IREDUHIGHST2 == 10 ~ 5, #associates degree
      IREDUHIGHST2 == 11 ~ 6, #college graduate or higher
      TRUE ~ NA_real_
    ),
    insurance_type = case_when(
      IRINSUR4 == 2 ~ 0, #not covered
      IRMEDICR == 1 ~ 1, #covered by medicare
      IRMCDCHP == 1 ~ 2, #covered by medicaid/chip
      IRPRVHLT == 1 & GRPHLTIN == 1 ~ 3, #covered by private, through employer
      IRPRVHLT == 1 & GRPHLTIN == 2 ~ 4, #covered by private, elsewhere
      TRUE ~ NA_real_
    ),
      private_coverage = case_when(
        IRPRVHLT == 2 ~ 1, #not covered
        HLTINALC == 1 & HLTINDRG == 1 & HLTINMNT == 1 ~ 2, #covers for alcohol, drug, and mental health
        HLTINALC == 1 & HLTINDRG == 1 & HLTINMNT == 2 ~ 3, #covers for alcohol and drug
        HLTINALC == 1 & HLTINDRG == 2 & HLTINMNT == 1 ~ 4, #covers for alcohol and mental health
        HLTINALC == 2 & HLTINDRG == 1 & HLTINMNT == 1 ~ 5, #covers for drugs and mental health
        HLTINALC == 1 & HLTINDRG == 2 & HLTINMNT == 2 ~ 6, #covers for alcohol only
        HLTINALC == 2 & HLTINDRG == 1 & HLTINMNT == 2 ~ 7, #covers for drugs only
        HLTINALC == 2 & HLTINDRG == 2 & HLTINMNT == 1 ~ 8, #covers for mental health only
        TRUE ~ NA_real_
    ),
      college_educated = case_when(
      education_level == 5 | education_level == 6 ~ 1, # college educated
      education_level == 1 | education_level == 2 | education_level == 3 | education_level == 4 ~ 2, # not college educated
      TRUE ~ NA_real_
    ),
      health_binary = case_when(
      HEALTH2 == 1 | HEALTH2 == 2 ~ 1, # good health
      HEALTH2 == 3 | HEALTH2 == 4 ~ 2, # bad health
      TRUE ~ NA_real_
    ), 
    coverage_01 = case_when(
      IRINSUR4 == 2 ~ 0, #not covered
      IRINSUR4 == 1 ~ 1, #covered
      TRUE ~ NA_real_
    )
  )

```  

```{r rename}

colnames(data_subset_one)[colnames(data_subset_one) == "QUESTID2"] <- "id"
colnames(data_subset_one)[colnames(data_subset_one) == "CATAG6"] <- "age"
colnames(data_subset_one)[colnames(data_subset_one) == "HEALTH2"] <- "health"
colnames(data_subset_one)[colnames(data_subset_one) == "IRSEX"] <- "sex"
colnames(data_subset_one)[colnames(data_subset_one) == "NEWRACE2"] <- "race"
colnames(data_subset_one)[colnames(data_subset_one) == "SEXRACE"] <- "sex_race"
colnames(data_subset_one)[colnames(data_subset_one) == "HLCNOTYR"] <- "insurance_12"
colnames(data_subset_one)[colnames(data_subset_one) == "IRINSUR4"] <- "insurance_binary"
colnames(data_subset_one)[colnames(data_subset_one) == "GOVTPROG"] <- "govt_prog"
colnames(data_subset_one)[colnames(data_subset_one) == "POVERTY3"] <- "poverty"
colnames(data_subset_one)[colnames(data_subset_one) == "IRWRKSTAT"] <- "employment"
colnames(data_subset_one)[colnames(data_subset_one) == "COCLNEGMH"] <- "covid_mental"
colnames(data_subset_one)[colnames(data_subset_one) == "COCLFINANC"] <- "covid_financial"
colnames(data_subset_one)[colnames(data_subset_one) == "COMHAPTDL2"] <- "covid_appt"
colnames(data_subset_one)[colnames(data_subset_one) == "COMHTELE2"] <- "covid_tele"
colnames(data_subset_one)[colnames(data_subset_one) == "COMHAPTDL2"] <- "covid_appt"
colnames(data_subset_one)[colnames(data_subset_one) == "COMHRXDL2"] <- "covid_prescrip"
colnames(data_subset_one)[colnames(data_subset_one) == "COMHSVHLT2"] <- "covid_care"

```

```{r finaldata}

#Create subset with variables desired
final_data <- data_subset_one[, c("id", "age", "health", "education_level", 
                                  "sex", "race", "sex_race", "college_educated",
                                  "health_binary",
                                     
                                  "insurance_type", "private_coverage","insurance_12", 
                                  "insurance_binary", "coverage_01",
                                     
                                  "govt_prog", "poverty", "employment",
                                     
                                  "covid_mental", "covid_financial", "covid_tele", "covid_appt",
                                  "covid_prescrip", "covid_care",
                                     
                                  "depression_score", "anxiety_score", "mental_health_score", 
                                  "depression_status", "anxiety_status", "mental_health_status")]
final_data


```

```{r chi2_race}
#Is there a significant difference in insurance type and coverage between different races?

#Remove empty variables
final_data_clean1 <- final_data[!is.na(final_data$insurance_type) & !is.na(final_data$race), ]

#Chi Square Test
chi_race_insurance_test <- chisq.test(final_data_clean1$insurance_type, final_data_clean1$race)
chi_race_insurance_test

#Contingency Table
table(final_data_clean1$insurance_type, final_data_clean1$race)

#Plot
ggplot(final_data_clean1, aes(x = race, fill = insurance_type)) +
  geom_bar(position = "fill") +
    labs(title = "Insurance Type Distribution by Race",
       y = "Proportion", x = "Race") +
  scale_x_discrete(guide = guide_axis(angle=30),
                   labels = c("1" = "White",
                              "2" = "African American",
                              "3" = "Native American",
                              "4" = "Native Hawaiian",
                              "5" = "Asian",
                              "6" = "More than one race",
                              "7" = "Hispanic")) +
  scale_fill_discrete(name = "Insurance Coverage",
                      labels = c("0" = "Not Covered",
                                 "1" = "Medicare",
                                 "2" = "Medicaid/Chip",
                                 "3" = "Private, employer",
                                 "4" = "Private, elsewhere")) +
      theme_minimal() 
  
```


```{r chi2_poverty}
#Is there a significant difference in insurance type and coverage between different poverty levels?
final_data_clean2 <- final_data[!is.na(final_data$insurance_type) & !is.na(final_data$poverty), ]

#Chi Square Test
chi_poverty_insurance_test <- chisq.test(final_data_clean1$insurance_type, final_data_clean1$poverty)
chi_poverty_insurance_test

#Contingency Table
table(final_data_clean2$insurance_type, final_data_clean2$poverty)

#Plot
ggplot(final_data_clean2, aes(x = poverty, fill = insurance_type)) +
  geom_bar(position = "fill") +
    labs(title = "Insurance Type Distribution by Poverty Level",
       y = "Proportion", x = "Poverty Level") +
    scale_x_discrete(guide = guide_axis(angle=20),
                   labels = c("1" = "Living in Poverty",
                              "2" = "Income up to 2x FPL",
                              "3" = "Income More than 2x FPL")) +
  scale_fill_discrete(name = "Insurance Coverage",
                      labels = c("0" = "Not Covered",
                                 "1" = "Medicare",
                                 "2" = "Medicaid/Chip",
                                 "3" = "Private, employer",
                                 "4" = "Private, elsewhere")) +
  theme_minimal() 

```

```{r manova_mental}
#Is there a significant difference in depression status and anxiety status between those with/without insurance? 

manova_result <- manova(cbind(depression_status, anxiety_status) ~ coverage_01, data = final_data)
summary(manova_result)

```






